name: Executar script Python a cada 30 minutos

on:
  schedule:
    - cron: '30 11 * * 1-5'
    - cron: '30 12 * * 1-5'
    - cron: '30 13 * * 1-5'
    - cron: '30 14 * * 1-5'
    - cron: '30 16 * * 1-5'
    - cron: '30 17 * * 1-5'
    - cron: '30 18 * * 1-5'
    - cron: '30 19 * * 1-5'
    - cron: '30 20 * * 1-5'
    - cron: '30 21 * * 1-5'
  workflow_dispatch:  # Permite executar manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Clonar o repositório
        uses: actions/checkout@v3

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: 📦 Instalar dependências
        run: |
          pip install pandas zeep google-auth google-api-python-client python-dateutil

      - name: 🔐 Criar credenciais do Google
        run: |
          echo '${{ secrets.GOOGLE_CREDS }}' > credenciais.json

      - name: ▶️ Executar o script
        env:
          USUARIO_WS: ${{ secrets.USUARIO_WS }}
          SENHA_WS: ${{ secrets.SENHA_WS }}
        run: python main.py

