name: Executar script Python a cada 30 minutos

on:
  schedule:
    # Das 11h às 13h59 – a cada 30 minutos
    - cron: '0,30 11-13 * * 1-5'
    # Das 14h às 22h – uma vez por hora
    - cron: '0 14-22 * * 1-5'
  workflow_dispatch:         # Permite executar manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Clonar o repositório
        uses: actions/checkout@v3

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: 📦 Instalar dependências
        run: |
          pip install pandas zeep google-auth google-api-python-client python-dateutil

      - name: 🔐 Criar credenciais do Google
        run: |
          echo '${{ secrets.GOOGLE_CREDS }}' > credenciais.json

      - name: ▶️ Executar o script
        env:
          USUARIO_WS: ${{ secrets.USUARIO_WS }}
          SENHA_WS: ${{ secrets.SENHA_WS }}
        run: python main.py

