name: Executar script Python a cada 30 minutos

on:
  schedule:
    - cron: '*/30 * * * *'  # Executa a cada 30 minutos
  workflow_dispatch:         # Permite executar manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Clonar o repositório
        uses: actions/checkout@v3

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: 📦 Instalar dependências
        run: |
          pip install pandas zeep google-auth google-api-python-client python-dateutil

      - name: 🔐 Criar credenciais do Google
        run: |
          echo '${{ secrets.GOOGLE_CREDS }}' > credenciais.json

      - name: ▶️ Executar o script
        run: python main.py
